# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AS-8X API Documentation
theme: just-the-docs

nav_external_links: false

aux_links_new_tab: true
aux_links:
  "AS-8X on GitHub":
    - "//github.com/armsoft//as8x-docs"

back_to_top: true
back_to_top_text: "↑ Back to top"

color_scheme: light

callouts_level: quiet # or loud
callouts:
  important:
    title: Կարևոր
    color: blue
  note:
    title: Նկատառում
    color: purple
  warning:
    title: Զգուշացում
    color: red

compress_html:
  ignore:
    envs: all

defaults:
  -
    scope:
      path: "src"
    values:
      layout: "page"

toc: true

versions:
  - id: bank
    product: "ՀԾ-Բանկ"
    versions: ["250626.000", "250929.000"]
  - id: enterprise
    product: "ՀԾ-Ձեռնարկություն"
    versions: ["4.0060.0", "4.0061.0"]
  - id: wages
    product: "ՀԾ-Աշխատավարձ"
    versions: ["4.0061.0", "4.0062.0"]